# Generated by Django 3.1.3 on 2021-12-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_alter_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
