# Generated by Django 3.2.9 on 2021-12-08 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproject',
            name='hide',
            field=models.BooleanField(default=True),
        ),
    ]
