# Generated by Django 3.2.9 on 2021-11-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postproject',
            options={'verbose_name': 'Post projects', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='tagsprojects',
            options={'verbose_name': 'tags Projects', 'verbose_name_plural': 'TagsUsers Projects'},
        ),
        migrations.AlterField(
            model_name='postproject',
            name='end_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='postproject',
            name='start_price',
            field=models.IntegerField(),
        ),
    ]
