# Generated by Django 3.2.9 on 2021-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_postproject_hide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
