# Generated by Django 3.2.9 on 2021-12-09 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_alter_postproject_hide'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postproject',
            options={'ordering': ['-created_project'], 'verbose_name': 'project', 'verbose_name_plural': 'Projects'},
        ),
    ]
