# Generated by Django 3.2.9 on 2021-11-24 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_alter_postproject_user_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproject',
            old_name='user_profile',
            new_name='user',
        ),
    ]
