# Generated by Django 3.2.9 on 2021-12-02 19:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0005_rename_user_profile_postproject_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproject',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
