# Generated by Django 3.2.9 on 2021-12-02 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0006_postproject_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsprojects',
            name='tags_users_projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_users_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
