# Generated by Django 3.2.9 on 2021-12-16 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0006_auto_20211214_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagsJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
                ('tags_users_jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_users_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tags jobs',
                'verbose_name_plural': 'TagsUsers jobs',
            },
        ),
        migrations.CreateModel(
            name='PostJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_jobs', models.CharField(max_length=100)),
                ('type_work_project', models.CharField(max_length=100)),
                ('epic_coder', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description_job', models.TextField()),
                ('hide', models.BooleanField(default=False)),
                ('updated_job', models.DateTimeField(auto_now=True)),
                ('created_job', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_post_jobs', to=settings.AUTH_USER_MODEL)),
                ('skills_tags_jobs', models.ManyToManyField(blank=True, to='posting.TagsJobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_job'],
            },
        ),
    ]
