# Generated by Django 3.2.9 on 2021-12-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0007_postjobs_tagsjobs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postjobs',
            old_name='type_work_project',
            new_name='type_work_job',
        ),
    ]
