# Generated by Django 3.2.9 on 2021-12-03 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0007_alter_tagsprojects_tags_users_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagsprojects',
            name='tags_users_projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
