# Generated by Django 3.2.9 on 2021-12-16 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0008_rename_type_work_project_postjobs_type_work_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobs',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
