# Generated by Django 3.2.9 on 2021-12-16 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0009_postjobs_saved_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postjobs',
            name='saved_jobs',
        ),
    ]
