# Generated by Django 3.2.9 on 2021-12-07 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0009_alter_tagsprojects_tags_users_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postproject',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_post_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
