# Generated by Django 3.2.9 on 2021-12-22 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posting', '0010_remove_postjobs_saved_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='postjobs',
            name='viewers_job',
            field=models.ManyToManyField(blank=True, related_name='viewers_job', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postproject',
            name='viewers_project',
            field=models.ManyToManyField(blank=True, related_name='viewers_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
