# Generated by Django 3.2.9 on 2021-12-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversations', '0005_auto_20211215_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='im_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_message', to='accounts.account'),
            preserve_default=False,
        ),
    ]
