# Generated by Django 3.2.9 on 2021-12-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0006_auto_20211215_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created', '-updated'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
    ]
