# Generated by Django 3.2.9 on 2021-12-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tag users',
            },
        ),
        migrations.CreateModel(
            name='Ask_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_question', models.DateTimeField(auto_now_add=True)),
                ('updated_question', models.DateTimeField(auto_now=True)),
                ('tag_question', models.ManyToManyField(blank=True, related_name='tag_question', to='ask_questions.TagsQuestions')),
            ],
        ),
    ]
