# Generated by Django 3.2.9 on 2021-12-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_questions', '0002_auto_20211224_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ask_questions',
            options={'verbose_name': 'question', 'verbose_name_plural': 'Ask_questions'},
        ),
        migrations.RemoveField(
            model_name='ask_questions',
            name='description',
        ),
    ]
