# Generated by Django 3.2.9 on 2021-12-24 17:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask_questions', '0003_auto_20211224_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='ask_questions',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ask_questions',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers_questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
