# Generated by Django 3.2.9 on 2021-12-27 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('photo_profile', models.ImageField(default='avatar/avatar_ixe80o.png', null=True, upload_to='userprofile/%Y/%m/%d')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('overview', models.TextField(blank=True)),
                ('photo_cover', models.ImageField(blank=True, default='avatar/cover_kgtasa.jpg', null=True, upload_to='cover/%Y/%m/%d')),
                ('education_title', models.CharField(blank=True, max_length=100)),
                ('education_year_start', models.IntegerField(blank=True, null=True)),
                ('education_year_end', models.IntegerField(blank=True, null=True)),
                ('education_description', models.TextField(blank=True, null=True)),
                ('location_country', models.CharField(blank=True, max_length=100)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('hourly_work', models.IntegerField(blank=True, null=True)),
                ('type_work', models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Part time', 'Part time'), ('Full time', 'Full time')], default=None, max_length=50, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
