# Generated by Django 3.1.3 on 2021-11-09 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hourly_work',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='type_work',
            field=models.CharField(blank=True, choices=[('full time', 'part time')], max_length=50),
        ),
    ]
