# Generated by Django 3.2.9 on 2021-12-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('user_profile', '0001_initial'),
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_user', to='user_profile.experience_user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='links_media',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_media', to='user_profile.social_media'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='my_bids_projects',
            field=models.ManyToManyField(blank=True, to='posting.PostProject'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to='posting.PostJobs'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_tags_user',
            field=models.ManyToManyField(blank=True, related_name='skills_tags_user', to='user_profile.TagsUser'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
