# Generated by Django 3.2.9 on 2021-11-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/%Y/%m/%d'),
        ),
    ]
