# Generated by Django 3.2.9 on 2021-11-09 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills_tags',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills_tags',
            field=models.ManyToManyField(blank=True, to='accounts.Tags'),
        ),
    ]
