# Generated by Django 3.2.9 on 2021-11-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211112_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_work',
            field=models.CharField(blank=True, choices=[('part time', 'part time'), ('full time', 'full time')], max_length=50, null=True),
        ),
    ]
