# Generated by Django 3.2.9 on 2021-11-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20211109_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='user_tags',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
