# Generated by Django 3.2.9 on 2021-11-20 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_photo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo_cover',
            field=models.ImageField(blank=True, default='avatar/cover.png', null=True, upload_to='cover/%Y/%m/%d'),
        ),
    ]
