# Generated by Django 3.2.9 on 2021-12-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20211209_0210'),
        ('accounts', '0003_userprofile_commentjobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='commentjobs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='comment_jobs',
            field=models.ManyToManyField(blank=True, related_name='comment_jobs', to='comment.CommentJobs'),
        ),
    ]
