# Generated by Django 3.2.9 on 2021-12-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211209_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='comment_jobs',
        ),
    ]
