# Generated by Django 3.2.9 on 2021-12-31 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211230_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hourly_work',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='type_work',
        ),
    ]
