# Generated by Django 3.2.9 on 2021-11-12 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_type_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hourly_work',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
