# Generated by Django 3.2.9 on 2021-11-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_photo_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills_tags',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Tags'),
        ),
    ]
