# Generated by Django 3.2.9 on 2021-12-07 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
