# Generated by Django 3.2.9 on 2021-11-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20211112_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='user_tags',
            new_name='tags_user',
        ),
    ]
