# Generated by Django 3.2.9 on 2021-11-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_work',
            field=models.CharField(blank=True, choices=[('Hourly', 'Hourly'), ('Part time', 'Part time'), ('Full time', 'Full time')], default=None, max_length=50, null=True),
        ),
    ]
