# Generated by Django 3.2.9 on 2021-12-07 15:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='saved_jobs',
            field=models.ManyToManyField(blank=True, related_name='saved_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
