# Generated by Django 3.2.9 on 2021-11-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_userprofile_type_work'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='TagsUser',
        ),
    ]
