# Generated by Django 3.2.9 on 2021-11-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_user_tags_tags_tags_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='photo_cover',
            field=models.ImageField(null=True, upload_to='cover/%Y/%m/%d'),
        ),
    ]
