# Generated by Django 3.2.9 on 2021-11-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_tags_tagsuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagsuser',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tagUsers'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='skills_tags',
            new_name='skills_tags_user',
        ),
    ]
