# Generated by Django 3.2.9 on 2021-11-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20211122_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='skills_tags_user',
            field=models.ManyToManyField(blank=True, to='accounts.TagsUser'),
        ),
    ]
