# Generated by Django 3.2.9 on 2021-12-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20211214_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='saved_jobs',
        ),
    ]
