# Generated by Django 3.2.9 on 2021-12-23 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_userprofile_saved_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='viewers',
            field=models.ManyToManyField(blank=True, related_name='viewers_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
