# Generated by Django 3.2.9 on 2021-12-23 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20211214_1838'),
        ('accounts', '0016_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='user_profile.experience_user'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='links_media',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_media', to='user_profile.social_media'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='skills_tags_user',
            field=models.ManyToManyField(blank=True, related_name='skills_tags_user', to='user_profile.TagsUser'),
        ),
    ]
