# Generated by Django 3.2.9 on 2021-12-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20211214_1838'),
        ('accounts', '0017_auto_20211223_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_user', to='user_profile.experience_user'),
        ),
    ]
