# Generated by Django 3.2.9 on 2021-12-24 22:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_userprofile_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
