# Generated by Django 3.2.9 on 2021-12-25 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20211224_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='education_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
