# Generated by Django 3.2.9 on 2021-12-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_userprofile_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='photo_profile',
            field=models.ImageField(default='avatar/avatar_ixe80o.png', null=True, upload_to='userprofile/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_cover',
            field=models.ImageField(blank=True, default='avatar/cover_kgtasa.jpg', null=True, upload_to='cover/%Y/%m/%d'),
        ),
    ]
