# Generated by Django 3.2.9 on 2021-11-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='name',
            field=models.CharField(blank=True, choices=[('facebook', 'facebook'), ('linkedin', 'linkedin'), ('instagram', 'instagram'), ('youtube', 'youtube'), ('twitter', 'youtube')], default=None, max_length=100, null=True),
        ),
    ]
