# Generated by Django 3.2.9 on 2021-12-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20211209_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentjobs',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comment Jobs'},
        ),
        migrations.AlterModelOptions(
            name='commentprojects',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comment Projects'},
        ),
        migrations.RenameField(
            model_name='commentjobs',
            old_name='jobs',
            new_name='jobs_profile',
        ),
        migrations.RenameField(
            model_name='commentprojects',
            old_name='post',
            new_name='post_project',
        ),
    ]
