# Generated by Django 3.2.9 on 2021-12-09 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20211209_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentjobs',
            old_name='user',
            new_name='user_job',
        ),
        migrations.RenameField(
            model_name='commentprojects',
            old_name='user',
            new_name='user_post',
        ),
    ]
