# Generated by Django 3.2.9 on 2021-12-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_auto_20211209_0210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentjobs',
            options={'ordering': ['-updated'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comment Jobs'},
        ),
        migrations.AlterModelOptions(
            name='commentprojects',
            options={'ordering': ['-updated'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comment Projects'},
        ),
        migrations.RenameField(
            model_name='commentjobs',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='commentprojects',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='commentjobs',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='commentprojects',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
