# Generated by Django 3.1.3 on 2021-12-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0005_auto_20211213_1724'),
        ('comment', '0007_auto_20211209_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentjobs',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commentprojects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commentprojects',
            name='post_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_project_comment', to='posting.postproject'),
        ),
    ]
