# Generated by Django 3.2.9 on 2021-12-16 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_remove_postjobs_saved_jobs'),
        ('comment', '0009_auto_20211214_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentjobs',
            name='jobs_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs_profile', to='posting.postjobs'),
        ),
    ]
