# Generated by Django 3.2.9 on 2021-12-20 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_remove_postjobs_saved_jobs'),
        ('comment', '0010_alter_commentjobs_jobs_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentjobs',
            name='jobs_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_job_comment', to='posting.postjobs'),
        ),
    ]
