# Generated by Django 3.2.9 on 2021-12-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_alter_commentjobs_jobs_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentjobs',
            old_name='jobs_profile',
            new_name='post_job',
        ),
    ]
