# Generated by Django 3.2.9 on 2021-12-11 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationjobs',
            options={'ordering': ['-created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notification Jobs'},
        ),
        migrations.AlterModelOptions(
            name='notificationprojects',
            options={'ordering': ['-created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notification Projects'},
        ),
    ]
