# Generated by Django 3.1.3 on 2021-12-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20211213_1724'),
        ('notifications', '0005_auto_20211213_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationprojects',
            options={'ordering': ['-created'], 'verbose_name': 'Notification', 'verbose_name_plural': 'Notification Projects Jobs'},
        ),
        migrations.AddField(
            model_name='notificationprojects',
            name='post_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_post_job', to='accounts.userprofile'),
        ),
        migrations.DeleteModel(
            name='NotificationJobs',
        ),
    ]
