# Generated by Django 3.2.9 on 2021-12-14 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_auto_20211213_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprojects',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
