# Generated by Django 3.2.9 on 2021-12-20 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0010_remove_postjobs_saved_jobs'),
        ('notifications', '0007_alter_notificationprojects_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationprojects',
            name='post_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_post_job', to='posting.postjobs'),
        ),
    ]
